name: styled_text
description: Text widget with formatted text using tags. Makes it easier to use formatted text in multilingual applications.
version: 8.1.0
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/styled_text_package/tree/master/styled_text
repository: https://github.com/andyduke/styled_text_package
issue_tracker: https://github.com/andyduke/styled_text_package/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  xmlstream: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
